### ISSUE TITLE
Outbound Scheduling Problem

### ISSUE THREAD

**Issue by tonypearl** [chadsmith/OpenVBX-Plugin-Outbound#10]
Hello!

This issue has been driving me nuts. 
Here's the simple problem: I set up an OutBound Call Flow to go out to a LIST (even a small one of only 1 person), and it doesn't happen. The OB SMS does work, but NOT the Call flow, no matter which one I test.

So I check my error logs & this is what I see (repeating every 5 minutes - the same interval I use for the Cron job). Please note that I have my OpenVBX installed & configured on a subdomain):

**PHP Fatal error:  Uncaught exception 'Services_Twilio_RestException' with message 'Url is not a valid URL: http://home/USERNAME/public_html/xxx/plugins/Outboundmod/twiml/start/voice/1' in /home/xxxxxx/public_html/xxx/OpenVBX/libraries/Services/Twilio.php:305
Stack trace:
#0 /home/xxxxxx/public_html/xxx/OpenVBX/libraries/Services/Twilio.php(229): Services_Twilio->_processResponse(Array)
#1 /home/xxxxxx/public_html/xxx/OpenVBX/libraries/Services/Twilio/ListResource.php(92): Services_Twilio->createData('/2010-04-01/Acc...', Array)
#2 /home/xxxxxx/public_html/xxx/OpenVBX/libraries/Services/Twilio/Rest/Calls.php(25): Services_Twilio_ListResource->_create(Array)
#3 /home/xxxxxx/public_html/xxx/plugins/Outboundmod/queue.php(16): Services_Twilio_Rest_Calls->create('+1xxxxxxxxxx', '+1xxxxxxxxx', 'http://home/now...')
#4 /home/xxxxxx/public_html/xxx/OpenVBX/controllers/hook.php(48): require('/home/nowshare/...')
#5 [internal function]: Hook->index('outbound', 'cron')
#6 /home/xxxxxx/public_html/xxx/system/codeigniter/Code in /home/xxxxxx/public_html/xxx/OpenVBX/libraries/Services/Twilio.php on line 305**

(the +1xxxxxxxxxx, Username & exact locations above were altered for privacy)

**Comment by minaevd** [comment]
seems like an issue is related to the return value of the site_url function - the "uri" is formed with the following code: 'uri' => site_url('twiml/start/voice/' . $flow[0]->values['id'])
This site_url is tied to the "base_url" setting, so I suspect that you modified your OpenVBX/config/config.php file and set a wrong 'base_url'.

--
Dmitry Minaev
CEO & Founder of Verbery - cloud based OpenVBX
https://www.verbery.com/

**Comment by tonypearl** [comment]
Thanks for your reply, Dmitry! Appreciated.
But I had not modified that file. I suspect that there MAY be an issue w/ this because it's a subdomain (here.mysite.com)
But the weird thing is that this is ONLY happening on the CALL flows, not the SMS ones. 
Any thoughts on this now?
Thanks!

**Comment by minaevd** [comment]
It's different code for sms and call. So, what's in you config for base_url?
You can send me a direct message and I'll help you with your issue since it doesn't seem to be an issue with the code of this plugin: support@verbery.com

**Comment by tonypearl** [comment]
Sweet - how awesome!!
Will do. Sending you a message in a few. 
Thanks!!
